export const SUPPORTED_LANGUAGES = [
  { value: 'javascript', label: 'JavaScript' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'csharp', label: 'C#' },
  { value: 'go', label: 'Go' },
  { value: 'rust', label: 'Rust' },
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'sql', label: 'SQL' },
];

export const SYNTAX_THEMES = [
  { value: 'default', label: 'Default' },
  { value: 'a11yDark', label: 'A11y Dark' },
  { value: 'a11yLight', label: 'A11y Light' },
  { value: 'atomDark', label: 'Atom Dark' },
  { value: 'base16AteliersulphurpoolLight', label: 'Base16 Light' },
  { value: 'cb', label: 'CB' },
  { value: 'coldarkCold', label: 'Coldark Cold' },
  { value: 'coldarkDark', label: 'Coldark Dark' },
  { value: 'coyWithoutShadows', label: 'Coy (No Shadows)' },
  { value: 'coy', label: 'Coy' },
  { value: 'darcula', label: 'Darcula' },
  { value: 'dark', label: 'Dark' },
  { value: 'dracula', label: 'Dracula' },
  { value: 'duotoneDark', label: 'Duotone Dark' },
  { value: 'duotoneEarth', label: 'Duotone Earth' },
  { value: 'duotoneForest', label: 'Duotone Forest' },
  { value: 'duotoneLight', label: 'Duotone Light' },
  { value: 'duotoneSea', label: 'Duotone Sea' },
  { value: 'duotoneSpace', label: 'Duotone Space' },
  { value: 'funky', label: 'Funky' },
  { value: 'ghcolors', label: 'GitHub Colors' },
  { value: 'gruvboxDark', label: 'Gruvbox Dark' },
  { value: 'gruvboxLight', label: 'Gruvbox Light' },
  { value: 'holiTheme', label: 'Holi' },
  { value: 'hopscotch', label: 'Hopscotch' },
  { value: 'lucario', label: 'Lucario' },
  { value: 'materialDark', label: 'Material Dark' },
  { value: 'materialLight', label: 'Material Light' },
  { value: 'materialOceanic', label: 'Material Oceanic' },
  { value: 'nightOwl', label: 'Night Owl' },
  { value: 'nord', label: 'Nord' },
  { value: 'okaidia', label: 'Okaidia' },
  { value: 'oneDark', label: 'One Dark' },
  { value: 'oneLight', label: 'One Light' },
  { value: 'pojoaque', label: 'Pojoaque' },
  { value: 'prism', label: 'Prism' },
  { value: 'shadesOfPurple', label: 'Shades of Purple' },
  { value: 'solarizedDarkAtom', label: 'Solarized Dark Atom' },
  { value: 'solarizedlight', label: 'Solarized Light' },
  { value: 'synthwave84', label: 'Synthwave84' },
  { value: 'tomorrow', label: 'Tomorrow' },
  { value: 'twilight', label: 'Twilight' },
  { value: 'vsDark', label: 'VS Dark' },
  { value: 'vs', label: 'Visual Studio' },
  { value: 'vscDarkPlus', label: 'VS Code Dark+' },
  { value: 'xonokai', label: 'Xonokai' },
  { value: 'zTouch', label: 'Z-Touch' },
];
